### ISSUE TITLE
package 'html-redirections' not found

### ISSUE THREAD

**Issue by strdr4605** [allindevelopers/html-redirections#2]
https://www.npmjs.com/package/html-redirections

**Comment by unrevised6419** [comment]
🤔 GitHub and NPM reported that this package was unused, and I removed it. I will publish it back under `@allindevelopers/html-redirections` in a moment.

**Comment by unrevised6419** [comment]
Please see [`@allindevelopers/html-redirections@1.1.1`](https://www.npmjs.com/package/@allindevelopers/html-redirections/v/1.1.1)

https://github.com/allindevelopers/html-redirections/releases/tag/v1.1.1

**Comment by unrevised6419** [comment]
Published v1.1.2 that adds back the `html-redirections` bin

**Comment by unrevised6419** [comment]
Strange 🤔 it worked with v1.1.1 too 

https://github.com/strdr4605/strdr4605.github.io/actions/runs/11092451720/job/30817511323#step:6:283

**Comment by strdr4605** [comment]
Thanks🤝
